packages:
  - .

allowBuilds:
  '@ffmpeg-installer/darwin-arm64': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
